providers:
  github:
    classic:
      DBM-Classic:
        source: https://github.com/DeadlyBossMods/DBM-Classic
  curseforge:
    classic:
      NugEnergy:
        id: "123"
      Weakauras:
        id: "456"
gameDir: "/home/charles/Games/battlenet/drive_c/Program Files (x86)/World of Warcraft"
